-- Glosario de AgileEA: definiciones que se muestran como tooltips.
-- Categoría = columna o concepto; valor '' = definición del concepto.
CREATE TABLE IF NOT EXISTS `glosario` (
  `id_glosario` int(11) NOT NULL AUTO_INCREMENT,
  `categoria` varchar(60) NOT NULL,
  `valor` varchar(120) NOT NULL DEFAULT '',
  `etiqueta` varchar(160) DEFAULT NULL,
  `descripcion` text NOT NULL,
  `orden` smallint(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_glosario`),
  UNIQUE KEY `uk_glosario` (`categoria`, `valor`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Carga inicial. Si ya existe, actualiza el texto (no borra lo que hayas agregado).
INSERT INTO `glosario` (`categoria`, `valor`, `etiqueta`, `descripcion`, `orden`) VALUES
('lifecycle', '', 'Ciclo de vida', 'Fase en la que está la aplicación dentro de su vida útil, desde que se planifica hasta que se retira. Con fechas por fase se arma el roadmap.', 0),
('lifecycle', 'Plan', NULL, 'Aplicación planificada o aprobada, todavía no incorporada al uso operativo.', 1),
('lifecycle', 'Phase In', NULL, 'Aplicación en implementación, transición o despliegue progresivo hacia el uso operativo.', 2),
('lifecycle', 'Active', NULL, 'Aplicación actualmente activa y en uso dentro del portfolio.', 3),
('lifecycle', 'Phase Out', NULL, 'Aplicación en proceso de retiro, reemplazo o reducción progresiva de uso.', 4),
('lifecycle', 'End of Life', NULL, 'Aplicación retirada o fuera de su ciclo de vida objetivo; no debería recibir nuevas inversiones funcionales salvo excepciones.', 5),
('business_criticality', '', 'Criticidad de negocio', 'Impacto que tendría para el negocio la indisponibilidad de la aplicación o capacidad.', 0),
('business_criticality', 'Administrative Service', NULL, 'Soporta tareas administrativas, con bajo impacto en las operaciones del negocio.', 1),
('business_criticality', 'Business Operational', NULL, 'Importante para las operaciones del día a día, pero no impacta críticamente los objetivos estratégicos.', 2),
('business_criticality', 'Business Critical', NULL, 'Vital para las operaciones y soporta directamente objetivos estratégicos. Una indisponibilidad prolongada impactaría significativamente a la organización.', 3),
('business_criticality', 'Mission Critical', NULL, 'Esencial para la misión core y los objetivos estratégicos. Incluso una breve indisponibilidad puede tener consecuencias severas.', 4),
('functional_fit', '', 'Ajuste funcional', 'Qué tan bien cubre la aplicación las necesidades funcionales del negocio (1 = peor, 4 = mejor).', 0),
('functional_fit', '1', '1 - Unreasonable', 'No cubre adecuadamente las necesidades funcionales actuales del negocio.', 1),
('functional_fit', '2', '2 - Insufficient', 'Presenta gaps funcionales importantes y requiere complementos o trabajo manual.', 2),
('functional_fit', '3', '3 - Appropriate', 'Cubre adecuadamente las necesidades actuales, con limitaciones menores.', 3),
('functional_fit', '4', '4 - Perfect', 'Cubre de forma integral las necesidades actuales y acompaña la evolución esperada.', 4),
('technical_fit', '', 'Ajuste técnico', 'Qué tan adecuada es la tecnología de la aplicación en estándares, operación, riesgo y arquitectura (1 = peor, 4 = mejor).', 0),
('technical_fit', '1', '1 - Inappropriate', 'No cumple criterios técnicos, operativos o de riesgo aceptables.', 1),
('technical_fit', '2', '2 - Unreasonable', 'Tiene limitaciones técnicas relevantes, deuda o riesgos que condicionan su sostenibilidad.', 2),
('technical_fit', '3', '3 - Adequate', 'Cumple adecuadamente las necesidades técnicas actuales, aunque no está totalmente alineada con el objetivo futuro.', 3),
('technical_fit', '4', '4 - Fully Appropriate', 'Está plenamente alineada con estándares técnicos, operación, riesgo y arquitectura objetivo.', 4),
('clasificacion', '', 'Clasificación', 'Rol de la capacidad en la estrategia del negocio.', 0),
('clasificacion', 'Estratégica', NULL, 'Función orientada al mercado que permite diferenciarse de los competidores. Posee alta varianza competitiva: con los mismos insumos, distintas organizaciones obtienen resultados distintos. Es el objeto prioritario de la inversión en transformación digital.', 1),
('clasificacion', 'Operativa', NULL, 'Actividad técnica obligatoria e indispensable para la existencia y viabilidad del negocio. Opera en flujos específicos y secuenciales con alcance delimitado, y su interrupción compromete la continuidad. Suele estar estandarizada, con baja varianza entre operadores maduros.', 2),
('clasificacion', 'Transversal', NULL, 'Sostiene el funcionamiento de la organización y el cumplimiento regulatorio. No pertenece a ningún dominio y aplica a todos. No genera valor comercial externo de forma directa, pero su degradación produce riesgos sistémicos.', 3),
('cadena_de_valor', '', 'Cadena de valor', 'Etapa de la cadena de valor upstream en la que opera la capacidad.', 0),
('cadena_de_valor', 'Exploración & Evaluación de Activos', NULL, 'Localizar yacimientos de crudo y gas natural bajo la superficie terrestre y ejecutar perforaciones iniciales para validar si el hallazgo es comercialmente explotable.', 1),
('cadena_de_valor', 'Planificación del Desarrollo de Activos', NULL, 'Una vez que el activo se declara viable, se diseñan las estrategias de explotación, la ingeniería de las instalaciones de superficie y el programa definitivo de perforación.', 2),
('cadena_de_valor', 'Desarrollo de Activos', NULL, 'Construcción física de la infraestructura industrial y perforación en masa de los pozos productores planificados.', 3),
('cadena_de_valor', 'Producción & Transporte', NULL, 'Extracción continua del hidrocarburo, su separación primaria en campo, el almacenamiento temporal y el despacho seguro hacia los sistemas de refinación o exportación.', 4),
('pace_layering', '', 'Pace layering', 'Ritmo de cambio esperado de la capacidad (modelo de Gartner).', 0),
('pace_layering', 'Commodity', NULL, 'Ritmo de cambio lento y estable. 70% del portafolio. Ciclo de 2 a 7 años.', 1),
('pace_layering', 'Differentiation', NULL, 'Ritmo de cambio moderado. 20% del portafolio. Ciclo de 1 a 2 años.', 2),
('pace_layering', 'Innovation', NULL, 'Ritmo de cambio rápido y experimental. 5 a 10% del portafolio. Ciclo de 2 a 6 meses.', 3),
('regulatory_impact', '', 'Impacto regulatorio', 'Grado en que la capacidad está sujeta a regulación y controles externos.', 0),
('regulatory_impact', 'Low', NULL, 'Impacto regulatorio bajo o indirecto; mayormente gobernanza interna.', 1),
('regulatory_impact', 'Medium', NULL, 'Existe cumplimiento relevante (contrataciones, documentación, controles) pero con menor frecuencia, mayor tolerancia de tiempo o impacto más indirecto.', 2),
('regulatory_impact', 'High', NULL, 'La capacidad está directamente regulada y requiere permisos, estudios o reportes obligatorios frecuentes, auditorías, y presenta riesgo de sanciones por no conformidad ambiental, de seguridad, integridad o medición.', 3),
('tipo_aplicacion', '', 'Tipo de aplicación', 'Origen de la aplicación.', 0),
('tipo_aplicacion', 'Comercial', NULL, 'Aplicación adquirida a un proveedor externo y utilizada bajo un modelo comercial de licenciamiento, suscripción o mantenimiento.', 1),
('tipo_aplicacion', 'Desarrollo', NULL, 'Aplicación desarrollada específicamente para la organización, de forma interna o a medida, para cubrir necesidades propias del negocio.', 2),
('tipo_aplicacion', 'Open Source', NULL, 'Aplicación distribuida bajo una licencia de código abierto, que permite usar, estudiar, modificar y redistribuir el software según sus términos.', 3),
('deployment', '', 'Despliegue', 'Dónde corre y quién opera la aplicación.', 0),
('deployment', 'On-Premise', NULL, 'Aplicación desplegada y operada sobre infraestructura administrada por la organización.', 1),
('deployment', 'SaaS', NULL, 'Aplicación consumida como servicio y operada principalmente por el proveedor, normalmente mediante una suscripción.', 2),
('deployment', 'Private Cloud', NULL, 'Aplicación desplegada sobre infraestructura cloud dedicada o aislada para la organización.', 3),
('deployment', 'Public Cloud', NULL, 'Aplicación desplegada sobre infraestructura de nube pública provista y operada por un tercero.', 4),
('deployment', 'Hybrid', NULL, 'Aplicación cuya arquitectura combina componentes On-Premise y/o nubes privadas y públicas.', 5),
('deployment', 'Hosted', NULL, 'Aplicación alojada en infraestructura de un tercero dedicada o administrada externamente, sin implicar necesariamente un modelo SaaS.', 6),
('modelo_comercial', '', 'Modelo comercial', 'Forma en que se adquiere el derecho de uso del software.', 0),
('modelo_comercial', 'Perpetual', NULL, 'Licencia comprada una vez con derecho de uso indefinido; normalmente se suma soporte y mantenimiento anual.', 1),
('modelo_comercial', 'Subscription', NULL, 'Derecho de uso por un período; al vencer, se renueva o se pierde el acceso.', 2),
('modelo_comercial', 'Usage Based', NULL, 'Se paga según el consumo medido (horas, transacciones, volumen de datos).', 3),
('modelo_comercial', 'Enterprise Agreement', NULL, 'Acuerdo corporativo que cubre un conjunto amplio de productos o usuarios por un período, con condiciones negociadas.', 4),
('modelo_comercial', 'Sin costo', NULL, 'Uso sin cargo: open source, incluido en otro contrato o sin cargo del proveedor.', 5),
('metrica_licencia', '', 'Métrica de licencia', 'Unidad con la que se cuenta la licencia.', 0),
('metrica_licencia', 'Named User', NULL, 'Asignada a una persona específica; solo esa persona puede usarla.', 1),
('metrica_licencia', 'Concurrent / Floating', NULL, 'Pool compartido: limita cuántas personas la usan al mismo tiempo, no quiénes.', 2),
('metrica_licencia', 'CPU / Core', NULL, 'Se licencia por procesadores o núcleos del servidor donde corre.', 3),
('metrica_licencia', 'Server / Instance', NULL, 'Se licencia por servidor o instancia instalada.', 4),
('metrica_licencia', 'Site', NULL, 'Uso ilimitado dentro de una ubicación física definida.', 5),
('metrica_licencia', 'Enterprise', NULL, 'Uso ilimitado en toda la organización.', 6),
('metrica_licencia', 'Usage', NULL, 'Se mide y paga por consumo.', 7),
('tipo_gasto', '', 'Tipo de gasto', 'Naturaleza contable del gasto.', 0),
('tipo_gasto', 'CAPEX', NULL, 'Inversión de capital: compra de activos o licencias perpetuas que se amortizan en varios años.', 1),
('tipo_gasto', 'OPEX', NULL, 'Gasto operativo recurrente del período: suscripciones, soporte y mantenimiento, servicios.', 2),
('time', '', 'Matriz TIME', 'Clasificación del portafolio de aplicaciones según ajuste funcional y técnico (Gartner / LeanIX).', 0),
('time', 'Tolerar', NULL, 'Buen ajuste técnico pero bajo ajuste funcional: se mantiene sin invertir en funcionalidad, minimizando su costo.', 1),
('time', 'Invertir', NULL, 'Alto ajuste funcional y técnico: aplicación en la que conviene seguir invirtiendo.', 2),
('time', 'Migrar', NULL, 'Alto ajuste funcional pero bajo ajuste técnico: aporta valor, pero su tecnología es un riesgo; conviene migrarla a una plataforma adecuada.', 3),
('time', 'Eliminar', NULL, 'Bajo ajuste funcional y técnico: candidata a retiro o consolidación.', 4),
('rol_aplicacion', '', 'Rol en la aplicación', 'Responsabilidad de una persona sobre la aplicación.', 0),
('rol_aplicacion', 'Application Business Owner', NULL, 'Responsable de negocio: define prioridades, aprueba cambios y responde por el valor que entrega la aplicación.', 1),
('rol_aplicacion', 'Application Technology Owner', NULL, 'Responsable técnico: arquitectura, operación, seguridad y ciclo de vida tecnológico de la aplicación.', 2),
('rol_aplicacion', 'Product Owner', NULL, 'Gestiona la evolución funcional y el backlog; es el nexo entre los usuarios y el equipo técnico.', 3),
('rol_aplicacion', 'Key User', NULL, 'Usuario referente: conoce el uso en profundidad, valida cambios y capacita a otros usuarios.', 4),
('rol_proveedor', '', 'Rol del contacto', 'Para qué se contacta a la persona del proveedor.', 0),
('rol_proveedor', 'Comercial', NULL, 'Cotizaciones, renovaciones y condiciones comerciales.', 1),
('rol_proveedor', 'Soporte técnico', NULL, 'Incidentes, consultas técnicas y mesa de ayuda del producto.', 2),
('rol_proveedor', 'Licenciamiento', NULL, 'Altas, bajas y cantidades de licencias, claves y servidores de licencias.', 3),
('rol_proveedor', 'Otro', NULL, 'Otro tipo de contacto.', 4),
('habilita_imputacion', '', 'Pagador', 'La organización puede recibir imputación de costos: aparece como pagadora en contratos y costos.', 0),
('madurez', '', 'Madurez', 'Nivel de madurez de una capacidad en cinco dimensiones: procesos, tecnología, datos, organización y desempeño (1 a 5).', 0),
('madurez', '1', '1 - Initial / Ad Hoc', 'Informal y dependiente de personas.', 1),
('madurez', '2', '2 - Managed / Repeatable', 'Repetible, con prácticas reconocibles pero poco formalizadas.', 2),
('madurez', '3', '3 - Defined / Standardized', 'Definido y estandarizado, con roles y reglas claras.', 3),
('madurez', '4', '4 - Measured / Quantitatively Managed', 'Medido y gestionado con indicadores.', 4),
('madurez', '5', '5 - Optimizing / Leading AI', 'Optimización continua, con modelos predictivos e IA.', 5),
('brecha', '', 'Brecha de madurez', 'Distancia entre la madurez objetivo y el promedio actual de las cinco dimensiones. Cerrarla implica llevar cada dimensión al nivel objetivo. El objetivo se carga por subcapacidad N3 (madurez_objetivo).', 0),
('nivel_process', '', 'Madurez · Procesos', 'Procesos: nivel de 1 a 5.', 0),
('nivel_process', '1', '1 - Initial / Ad Hoc', 'Informal y no documentado. Cada persona lo resuelve a su manera.', 1),
('nivel_process', '2', '2 - Managed / Repeatable', 'Secuencia habitual reconocible, sin documentación punta a punta.', 2),
('nivel_process', '3', '3 - Defined / Standardized', 'Documentado, con roles, entregables y tiempos definidos.', 3),
('nivel_process', '4', '4 - Measured / Quantitatively Managed', 'Gestionado por indicadores, con ciclo de revisión y ajuste.', 4),
('nivel_process', '5', '5 - Optimizing / Leading AI', 'Se optimiza de forma continua a partir de la evidencia que genera.', 5),
('nivel_technology', '', 'Madurez · Tecnología', 'Tecnología: nivel de 1 a 5.', 0),
('nivel_technology', '1', '1 - Initial / Ad Hoc', 'Herramientas de escritorio de uso individual, sin integración.', 1),
('nivel_technology', '2', '2 - Managed / Repeatable', 'Herramientas específicas de la disciplina, con carga y traspaso manual.', 2),
('nivel_technology', '3', '3 - Defined / Standardized', 'Plataforma estándar de la disciplina, con integración parcial al ecosistema.', 3),
('nivel_technology', '4', '4 - Measured / Quantitatively Managed', 'Integración entre plataformas, con datos disponibles en tiempo real o cercano.', 4),
('nivel_technology', '5', '5 - Optimizing / Leading AI', 'Automatización avanzada, con modelos predictivos incorporados al flujo.', 5),
('nivel_data', '', 'Madurez · Datos', 'Datos: nivel de 1 a 5.', 0),
('nivel_data', '1', '1 - Initial / Ad Hoc', 'Dato disperso, sin dueño ni criterio de calidad. Se reconstruye cada vez.', 1),
('nivel_data', '2', '2 - Managed / Repeatable', 'Dato con ubicación conocida y formato acordado, sin control de versiones.', 2),
('nivel_data', '3', '3 - Defined / Standardized', 'Estándares y dueño definidos, con reglas básicas de calidad y trazabilidad.', 3),
('nivel_data', '4', '4 - Measured / Quantitatively Managed', 'Dato certificado, versionado y disponible para consumo automatizado.', 4),
('nivel_data', '5', '5 - Optimizing / Leading AI', 'Dato como activo gobernado, base de modelos predictivos y de asistentes.', 5),
('nivel_organization', '', 'Madurez · Organización', 'Organización: nivel de 1 a 5.', 0),
('nivel_organization', '1', '1 - Initial / Ad Hoc', 'Sin rol definido. Depende del conocimiento de una persona.', 1),
('nivel_organization', '2', '2 - Managed / Repeatable', 'Responsable identificable, sin rol formalizado ni respaldo.', 2),
('nivel_organization', '3', '3 - Defined / Standardized', 'Roles formales y foros de decisión establecidos.', 3),
('nivel_organization', '4', '4 - Measured / Quantitatively Managed', 'Gobernanza activa entre áreas, con escalamiento definido.', 4),
('nivel_organization', '5', '5 - Optimizing / Leading AI', 'Cultura de mejora continua, con contraste sistemático contra la industria.', 5),
('nivel_performance', '', 'Madurez · Desempeño', 'Desempeño: nivel de 1 a 5.', 0),
('nivel_performance', '1', '1 - Initial / Ad Hoc', 'No se mide. El resultado se conoce cuando falla.', 1),
('nivel_performance', '2', '2 - Managed / Repeatable', 'Se registran resultados, sin indicador ni comparación sistemática.', 2),
('nivel_performance', '3', '3 - Defined / Standardized', 'Indicadores definidos y reportados, sin análisis periódico del desvío.', 3),
('nivel_performance', '4', '4 - Measured / Quantitatively Managed', 'Desempeño medido, analizado periódicamente y realimentado a la decisión.', 4),
('nivel_performance', '5', '5 - Optimizing / Leading AI', 'Desempeño anticipado por modelos, no solo medido a posteriori.', 5)
ON DUPLICATE KEY UPDATE `etiqueta` = VALUES(`etiqueta`), `descripcion` = VALUES(`descripcion`), `orden` = VALUES(`orden`);
